"""The Python module of a model declared in JSON (spec 14 §4, nivel 3): a `StructuredNLDoc`
written the way the models of `pron.models` are — docstring, `__template__`, one `Field` with
a description per field. A derivative of its declaration: the same declaration regenerates
the same module. Without a template given, one section per field.
"""

from __future__ import annotations

import re
from dataclasses import dataclass

from pron.mcp.schema.field_decl import FieldDecl
from pron.mcp.writes.arg_error import ArgError

HEADER = '"""Generated by `pron mcp` (spec 14 §4, nivel 3) from the declaration of {name};\nregenerated from it, never edited by hand."""\n'


@dataclass(frozen=True)
class ModelSource:
    """A model's name, fields, template and base: the module they make."""

    name: str
    fields: tuple[FieldDecl, ...]
    template: str | None = None
    base: tuple[str, str] = ("sldb", "StructuredNLDoc")

    @staticmethod
    def of(
        name: str, fields: list, template: str | None, base: tuple[str, str] | None
    ) -> "ModelSource":
        if not re.fullmatch(r"[A-Z][A-Za-z0-9]*", name or ""):
            raise ArgError(f"model name {name!r} is not a CamelCase identifier")
        decls = tuple(FieldDecl.of(f) for f in fields or [])
        if not decls:
            raise ArgError("a model needs at least one field")
        if len({d.name for d in decls}) < len(decls):
            raise ArgError("two fields with the same name")
        return ModelSource(name, decls, template, base or ("sldb", "StructuredNLDoc"))

    @property
    def snake(self) -> str:
        return re.sub(r"(?<!^)(?=[A-Z])", "_", self.name).lower()

    def default_template(self, head: str | None = None) -> str:
        """One section per field under `head` (the model's name, or its base's template);
        lists as bullet lists."""
        sections = [head or f"# {self.name}"]
        for f in self.fields:
            slot = (
                f"- ⸢rev,list•{f.name}⸥" if f.type == "list[str]" else f"⸢rev•{f.name}⸥"
            )
            sections.append(f"## {f.name.replace('_', ' ').capitalize()}\n\n{slot}")
        return "\n\n".join(sections) + "\n"

    def module(self, head: str | None = None) -> str:
        """The whole module, as text; `head` opens the default template."""
        module, cls = self.base
        template = (self.template or self.default_template(head)).strip()
        lines = [
            HEADER.format(name=self.name),
            "from typing import Literal  # noqa: F401\n",
            "from pydantic import Field\n",
            f"from {module} import {cls}\n\n",
            f"class {self.name}({cls}):",
            f'    """{self.name}, declared by an agent through `kb_model_create`."""\n',
            f"    __template__ = {_quoted(template)}\n",
            *(f.source() for f in self.fields),
        ]
        return "\n".join(lines) + "\n"


def _quoted(text: str) -> str:
    """Triple quotes when the text allows them, as the hand-written models; repr otherwise."""
    if '"""' in text or "\\" in text or text.endswith('"'):
        return repr(text)
    return f'"""{text}"""'
