model: SurfaceDoc
path: knowledge/surfaces/surface-pron-sexpr-execution-compose_executor.md
tags:
- domain:system_architecture
- entity:module
- impl:here
- kind:software
- representation.markdown
- source.document.markdown
- system:pron
- type.knowledge.surface
- workspace.knowledge.surfaces
hash_c: b583da8fb1d633dd5e782b2080e19e8f8db362999f47b3af3537816d4ea3dc2e
