doc_name: surface-pron-sexpr-compose_slots
sections:
- path: sexpr-compose-slots
  title: sexpr.compose_slots
  breadcrumbs:
  - sexpr.compose_slots
  about:
  - sexpr.compose_slots
  - sexpr compose slots
  - domain:system_architecture
  - entity:module
  - impl:here
  - kind:software
  - representation.markdown
  - source.document.markdown
  - system:pron
  - type.knowledge.surface
  - workspace.knowledge.surfaces
  semantic_tags:
  - domain:system_architecture
  - entity:module
  - impl:here
  - kind:software
  - representation.markdown
  - source.document.markdown
  - system:pron
  - type.knowledge.surface
  - workspace.knowledge.surfaces
  slug: sexpr-compose-slots
  level: 1
  line_start: 14
  line_end: 29
- path: sexpr-compose-slots/purpose
  title: Purpose
  breadcrumbs:
  - sexpr.compose_slots
  - Purpose
  about:
  - sexpr.compose_slots
  - sexpr compose slots
  - Purpose
  - purpose
  - domain:system_architecture
  - entity:module
  - impl:here
  - kind:software
  - representation.markdown
  - source.document.markdown
  - system:pron
  - type.knowledge.surface
  - workspace.knowledge.surfaces
  semantic_tags:
  - domain:system_architecture
  - entity:module
  - impl:here
  - kind:software
  - representation.markdown
  - source.document.markdown
  - system:pron
  - type.knowledge.surface
  - workspace.knowledge.surfaces
  slug: purpose
  level: 2
  line_start: 16
  line_end: 19
- path: sexpr-compose-slots/how-it-works
  title: How It Works
  breadcrumbs:
  - sexpr.compose_slots
  - How It Works
  about:
  - sexpr.compose_slots
  - sexpr compose slots
  - How It Works
  - how it works
  - domain:system_architecture
  - entity:module
  - impl:here
  - kind:software
  - representation.markdown
  - source.document.markdown
  - system:pron
  - type.knowledge.surface
  - workspace.knowledge.surfaces
  semantic_tags:
  - domain:system_architecture
  - entity:module
  - impl:here
  - kind:software
  - representation.markdown
  - source.document.markdown
  - system:pron
  - type.knowledge.surface
  - workspace.knowledge.surfaces
  slug: how-it-works
  level: 2
  line_start: 20
  line_end: 26
- path: sexpr-compose-slots/commands
  title: Commands
  breadcrumbs:
  - sexpr.compose_slots
  - Commands
  about:
  - sexpr.compose_slots
  - sexpr compose slots
  - Commands
  - commands
  - domain:system_architecture
  - entity:module
  - impl:here
  - kind:software
  - representation.markdown
  - source.document.markdown
  - system:pron
  - type.knowledge.surface
  - workspace.knowledge.surfaces
  semantic_tags:
  - domain:system_architecture
  - entity:module
  - impl:here
  - kind:software
  - representation.markdown
  - source.document.markdown
  - system:pron
  - type.knowledge.surface
  - workspace.knowledge.surfaces
  slug: commands
  level: 2
  line_start: 27
  line_end: 29
hash_c: d96ba636c7cbeaa42b49ca2b7457fe0dd66c8d50b76e25234bbde120ab242c8b
sections_version: '2'
