name: implements--SurfaceDoc:surface-pron-sexpr-dry_compose--SpecDoc:spec-05
path: knowledge/relations/implements--SurfaceDoc:surface-pron-sexpr-dry_compose--SpecDoc:spec-05.md
hash_c: ce3f46a087eb12de3f2c83af5665c6d9d7d142c14874919f4e4685aca1d65368
hash_d: 3ebabf4286a3b52c399ce2795093c39615b0e55f6d854c5d2e1c0b38d4d65d5b
semantic_tags:
- layer.topology
- representation.markdown
- source.document.markdown
- type.relation.instance
