model: RelationDoc
path: knowledge/relations/implements--SurfaceDoc:surface-pron-sexpr-dry_compose--SpecDoc:spec-11.md
tags:
- layer.topology
- representation.markdown
- source.document.markdown
- type.relation.instance
hash_c: f101c57be281d46efaf7b9a93316e0a557a144b70b8a01966df8c33b3e12e839
