name: surface-pron-sexpr-dry_compose
path: knowledge/surfaces/surface-pron-sexpr-dry_compose.md
hash_c: 03cfdb42d281786423a5a16211d00ff558267768cf2842fd637ae4c42f25da81
hash_d: e24e4a4fe5659ee54ab52cf481c41906fc59d9e962f186ad1852c573f61caf1b
semantic_tags:
- domain:system_architecture
- entity:module
- impl:here
- kind:software
- representation.markdown
- source.document.markdown
- system:pron
- type.knowledge.surface
- workspace.knowledge.surfaces
