name: surface-pron-sexpr-compose_executor
path: knowledge/surfaces/surface-pron-sexpr-compose_executor.md
hash_c: cc170b51d5ddc9951b98c899bee525d4d8fff09801bcdd735f61320848463ffc
hash_d: 85310c3762ef79cb0e3ea0d0ecaa4420fdde797a1880015bc2a156809facc6f4
semantic_tags:
- domain:system_architecture
- entity:module
- impl:here
- kind:software
- representation.markdown
- source.document.markdown
- system:pron
- type.knowledge.surface
- workspace.knowledge.surfaces
